/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_angelponce;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia PM
 */
public class Lab8_AngelPonce extends javax.swing.JFrame {

 
    /**
     * Creates new form Lab8_AngelPonce
     */
    public Lab8_AngelPonce() {
        initComponents();
        radio.add(rb_f);
        radio.add(rb_m);
        ResultSet rs;
        /*Dba db = new Dba("./Personas.mdb");
        db.conectar();
            try {
                db.query.execute("select nombre,apellido,edad,nacionalidad,lugarDeResidencia,sexo,"
                        + "numeroCuenta,profesion,lugarTrabajo,facultad,tipoPersona"
                        + " from personas");
                rs = db.query.getResultSet();
                while (rs.next()) {
                    personas.add(new Personas((String) rs.getObject(1), (String) rs.getObject(2),
                            (String) rs.getObject(3), (String) rs.getObject(4),
                            (String) rs.getObject(5), (String) rs.getObject(6), (int) rs.getObject(7),
                            (String) rs.getObject(8),(String) rs.getObject(9),(String) rs.getObject(10),
                    (String) rs.getObject(11)));
                    cuentas.add((int)rs.getObject(7));
                    //tipos.add(rs.getObject(11));
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
         */
        //JOptionPane.showMessageDialog(null, personas.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        apellidocrear = new javax.swing.JTextField();
        nombrecrear = new javax.swing.JTextField();
        nacionalidadcrear = new javax.swing.JTextField();
        residenciacrear = new javax.swing.JTextField();
        edadcrear = new javax.swing.JTextField();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        cuentacrear = new javax.swing.JTextField();
        profesioncrear = new javax.swing.JTextField();
        facultadcrear = new javax.swing.JTextField();
        lugartrabajocrear = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbtipopersona = new javax.swing.JComboBox<>();
        modificar = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        residencia = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rb_m1 = new javax.swing.JRadioButton();
        rb_f1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        profesion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        trabajo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        facultad = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbtipopersona1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        busquedaprimaria = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfprimaria = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        taprimaria = new javax.swing.JTextArea();
        busquedatipo = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        tftipo = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tatipos = new javax.swing.JTextArea();
        busquedalibre = new javax.swing.JDialog();
        tflibre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        talibre = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        radio = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel2.setText("Crear Personas");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Edad");

        jLabel6.setText("Nacionalidad");

        jLabel7.setText("Lugar de Residencia");

        jLabel8.setText("Sexo");

        jLabel9.setText("Numero de cuenta");

        jLabel10.setText("Profesion");

        jLabel11.setText("Lugar de trabajo");

        jLabel12.setText("Facultad");

        rb_m.setText("Masculino");

        rb_f.setText("Femenino");

        jButton7.setText("CREAR");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel13.setText("Tipo persona");

        cbtipopersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estudiante ", "docente ", "administrativo ", "ejecutivo ", "decano" }));

        javax.swing.GroupLayout crearLayout = new javax.swing.GroupLayout(crear.getContentPane());
        crear.getContentPane().setLayout(crearLayout);
        crearLayout.setHorizontalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(apellidocrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nombrecrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(edadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(nacionalidadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(residenciacrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_f))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cuentacrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(profesioncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lugartrabajocrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbtipopersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(facultadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(crearLayout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jButton7)))))))
                    .addGroup(crearLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearLayout.setVerticalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombrecrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidocrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nacionalidadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(residenciacrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_m)
                        .addComponent(rb_f)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cuentacrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(profesioncrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lugartrabajocrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(facultadcrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbtipopersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jLabel18.setText("Ingrese nuevo Nombre");

        jLabel19.setText("Ingrese nuevo Apellido");

        jLabel20.setText("Ingrese nueva Edad");

        jLabel21.setText("Ingrese nueva Nacionalidad");

        jLabel22.setText("Ingrese nuevo Lugar de Residencia");

        jLabel23.setText("Pongale nuevo Sexo pue");

        rb_m1.setText("Masculino");

        rb_f1.setText("Femenino");

        jLabel24.setText("Ingrese nuevo Numero de cuenta");

        jLabel25.setText("Ingrese nueva Profesion");

        jLabel26.setText("Ingrese nuevo Lugar de trabajo");

        jLabel27.setText("Ingrese nueva Facultad");

        jLabel28.setText("Ingrese nuevo Tipo persona");

        cbtipopersona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estudiante ", "docente ", "administrativo ", "ejecutivo ", "decano" }));

        jButton11.setText("MODIFICAR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jLabel29.setText("MODIFICAR");

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar.getContentPane());
        modificar.getContentPane().setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel29)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificarLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_m1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rb_f1))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addComponent(profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(18, 18, 18)
                            .addComponent(trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modificarLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(cbtipopersona1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modificarLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificarLayout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(residencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_m1)
                            .addComponent(rb_f1)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(cbtipopersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(125, 125, 125)))
        );

        jButton10.setText("Buscar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel17.setText("Ingresa llave primaria");

        taprimaria.setColumns(20);
        taprimaria.setRows(5);
        jScrollPane4.setViewportView(taprimaria);

        javax.swing.GroupLayout busquedaprimariaLayout = new javax.swing.GroupLayout(busquedaprimaria.getContentPane());
        busquedaprimaria.getContentPane().setLayout(busquedaprimariaLayout);
        busquedaprimariaLayout.setHorizontalGroup(
            busquedaprimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaprimariaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(busquedaprimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addGroup(busquedaprimariaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfprimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        busquedaprimariaLayout.setVerticalGroup(
            busquedaprimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busquedaprimariaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(busquedaprimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfprimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel14.setText("Ingrese el tipo (estudiante, docente, administrativo, ejecutivo o decano)");

        jButton8.setText("Buscar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        tatipos.setColumns(20);
        tatipos.setRows(5);
        jScrollPane2.setViewportView(tatipos);

        javax.swing.GroupLayout busquedatipoLayout = new javax.swing.GroupLayout(busquedatipo.getContentPane());
        busquedatipo.getContentPane().setLayout(busquedatipoLayout);
        busquedatipoLayout.setHorizontalGroup(
            busquedatipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedatipoLayout.createSequentialGroup()
                .addGroup(busquedatipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busquedatipoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(busquedatipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jLabel14)
                            .addComponent(tftipo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(busquedatipoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        busquedatipoLayout.setVerticalGroup(
            busquedatipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedatipoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tftipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel15.setText("Ingrese cualquier atributo");

        jButton9.setText("Buscar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        talibre.setColumns(20);
        talibre.setRows(5);
        jScrollPane3.setViewportView(talibre);

        jLabel16.setText("BUSQUEDA LIBRE");

        javax.swing.GroupLayout busquedalibreLayout = new javax.swing.GroupLayout(busquedalibre.getContentPane());
        busquedalibre.getContentPane().setLayout(busquedalibreLayout);
        busquedalibreLayout.setHorizontalGroup(
            busquedalibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedalibreLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(busquedalibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jButton9)
                    .addGroup(busquedalibreLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(busquedalibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tflibre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        busquedalibreLayout.setVerticalGroup(
            busquedalibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedalibreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(21, 21, 21)
                .addGroup(busquedalibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tflibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PERSONAS");

        jButton4.setText("Busqueda por llave primaria");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Buscar personas por tipo");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Búsqueda libre");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton5)
                        .addGap(49, 49, 49)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        crear.pack();
        crear.setModal(true);
        crear.setLocationRelativeTo(null);
        crear.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        boolean correcto = true;
        for (int i = 0; i < cuentas.size(); i++) {
            if (cuentas.get(i) == Integer.parseInt(cuentacrear.getText())) {
                JOptionPane.showMessageDialog(null, "Ya existe esa cuenta");
                correcto = false;
                break;
            }
        }
        if (correcto) {
            String sexocrear = "";
            int c = Integer.parseInt(cuentacrear.getText());
            if (rb_m.isSelected()) {
                sexocrear = "M";
            } else if (rb_f.isSelected()) {
                sexocrear = "F";
            }
            Personas p = new Personas(nombrecrear.getText(), apellidocrear.getText(), edadcrear.getText(), nacionalidadcrear.getText(),
                    residenciacrear.getText(), sexocrear, Integer.parseInt(cuentacrear.getText()), profesioncrear.getText(),
                    lugartrabajocrear.getText(), facultadcrear.getText(), (String) cbtipopersona.getSelectedItem());
            personas.add(p);

            Dba db = new Dba("Personas.mdb");
            db.conectar();
            try {
                db.query.execute("INSERT INTO personas"
                        + " (nombre,apellido,edad,nacionalidad,lugarDeResidencia,sexo,numeroCuenta,profesion,lugarTrabajo,"
                        + "facultad,tipoPersona)"
                        + " VALUES ('" + nombrecrear.getText()
                        + "', '" + apellidocrear.getText()
                        + "', '" + edadcrear.getText()
                        + "', '" + nacionalidadcrear.getText()
                        + "', '" + residenciacrear.getText()
                        + "', '" + sexocrear
                        + "', '" + c + "', '" + profesioncrear.getText() + "', '" + lugartrabajocrear.getText() + "', "
                        + "'" + facultadcrear.getText() + "', '" + (String) cbtipopersona.getSelectedItem() + "')");
                db.commit();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Creó una nueva persona!");
            cuentas.add(c);
            tipos.add((String) cbtipopersona.getSelectedItem());
            DefaultListModel modelo = (DefaultListModel) jList1.getModel();
            modelo.addElement(p);
            jList1.setModel(modelo);

            nombrecrear.setText("");
            apellidocrear.setText("");
            edadcrear.setText("");
            nacionalidadcrear.setText("");
            residenciacrear.setText("");
            cuentacrear.setText("");
            profesioncrear.setText("");
            lugartrabajocrear.setText("");
            facultadcrear.setText("");
            crear.setVisible(false);
            db.desconectar();
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        busquedaprimaria.pack();
        busquedaprimaria.setModal(true);
        busquedaprimaria.setLocationRelativeTo(null);
        busquedaprimaria.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if (tftipo.getText().equals("estudiante") || tftipo.getText().equals("docente")
                || tftipo.getText().equals("administrativo") || tftipo.getText().equals("ejecutivo")
                || tftipo.getText().equals("decano")) {
            String aux=tftipo.getText()+" ";
            //tatipos.append(tftipo.getText().toUpperCase());
            for (int i = 0; i < personas.size(); i++) {
                //JOptionPane.showMessageDialog(null, personas.get(i).getTipo());
                //JOptionPane.showMessageDialog(null, "tipo getText: "+tftipo.getText());
                System.out.println(personas.get(i).getTipo());
                System.out.println("tipo getText:"+tftipo.getText());
                if (aux.equals(personas.get(i).getTipo())) {
                    tatipos.append(personas.get(i).toString() + "\n\n");
                } else {
                    JOptionPane.showMessageDialog(null, "Mira mi codigo, no se por que no lo imprime");
                }
            }
            tftipo.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Tipo no válido");
            tftipo.setText("");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        for (int i = 0; i < personas.size(); i++) {
            if (tflibre.getText().equals(personas.get(i).getNombre())
                    || tflibre.getText().equals(personas.get(i).getApellido())
                    || tflibre.getText().equals(personas.get(i).getEdad())
                    || tflibre.getText().equals(personas.get(i).getNacionalidad())
                    || tflibre.getText().equals(personas.get(i).getResidencia())
                    || tflibre.getText().equals(personas.get(i).getSexo())
                    || tflibre.getText().equals(personas.get(i).getNumerocuenta())
                    || tflibre.getText().equals(personas.get(i).getProfesion())
                    || tflibre.getText().equals(personas.get(i).getLugartrabajo())
                    || tflibre.getText().equals(personas.get(i).getFacultad())
                    || tflibre.getText().equals(personas.get(i).getTipo())) {

                talibre.append(personas.get(i).toString() + "\n\n");
            }
        }
        tflibre.setText("");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        for (int i = 0; i < personas.size(); i++) {
            if (personas.get(i).getNumerocuenta() == Integer.parseInt(tfprimaria.getText())) {
                taprimaria.append(personas.get(i).toString()+"\n\n");
                break;
            }
        }
        tfprimaria.setText("");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        busquedatipo.pack();
        busquedatipo.setModal(true);
        busquedatipo.setLocationRelativeTo(null);
        busquedatipo.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        busquedalibre.pack();
        busquedalibre.setModal(true);
        busquedalibre.setLocationRelativeTo(null);
        busquedalibre.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (jList1.getSelectedIndex() >= 0) {
            String aux = personas.get(jList1.getSelectedIndex()).getNombre();
            personas.remove(jList1.getSelectedIndex());
            //eliminar
            Dba db = new Dba("./Personas.mdb");
            db.conectar();
            try {
                db.query.execute("delete from personas where nombre='" + aux + "'");
                db.commit();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
            DefaultListModel modelo = (DefaultListModel) jList1.getModel();
            modelo.removeElementAt(jList1.getSelectedIndex());
            jList1.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(null, "No hay nadie seleccionado para eliminar");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        int help=personas.get(jList1.getSelectedIndex()).getNumerocuenta();
        String sx="";
        personas.get(jList1.getSelectedIndex()).setNombre(nombre.getText());
        personas.get(jList1.getSelectedIndex()).setApellido(apellido.getText());
        personas.get(jList1.getSelectedIndex()).setEdad(edad.getText());
        personas.get(jList1.getSelectedIndex()).setNacionalidad(nacionalidad.getText());
        personas.get(jList1.getSelectedIndex()).setResidencia(residencia.getText());
        if(rb_m1.isSelected()){
            personas.get(jList1.getSelectedIndex()).setSexo("M");
            sx="M";
        }
        else if(rb_f1.isSelected()){
            personas.get(jList1.getSelectedIndex()).setSexo("F");
            sx="F";
        }
        personas.get(jList1.getSelectedIndex()).setNumerocuenta(Integer.parseInt(cuenta.getText()));
        personas.get(jList1.getSelectedIndex()).setProfesion(profesion.getText());
        personas.get(jList1.getSelectedIndex()).setLugartrabajo(trabajo.getText());
        personas.get(jList1.getSelectedIndex()).setFacultad(facultad.getText());
        personas.get(jList1.getSelectedIndex()).setTipo((String)cbtipopersona1.getSelectedItem());
        
        Personas p2 = new Personas(nombre.getText(),apellido.getText(),edad.getText(),
            nacionalidad.getText(),residencia.getText(),
            sx,Integer.parseInt(cuenta.getText()),profesion.getText(),trabajo.getText(),facultad.getText(),
            (String)cbtipopersona1.getSelectedItem());
        
        DefaultListModel modelo = (DefaultListModel)jList1.getModel();
        modelo.setElementAt(p2, jList1.getSelectedIndex());
        
        Dba db = new Dba("./Personas.mdb");
        db.conectar();
        try {
            //db.query.execute("update alumnos set nombre='Donald Trump' where cuenta=5000");
            db.query.execute("update personas set nombre='"+p2.getNombre()+"' where numeroCuenta="+help);
            db.query.execute("update personas set apellido='"+p2.getApellido()+"' where numeroCuenta="+help);
            db.query.execute("update personas set edad='"+p2.getEdad()+"' where numeroCuenta="+help);
            db.query.execute("update personas set nacionalidad='"+p2.getNacionalidad()+"' where numeroCuenta="+help);
            db.query.execute("update personas set lugarDeResidencia='"+p2.getResidencia()+"' where numeroCuenta="+help);
            db.query.execute("update personas set sexo='"+p2.getSexo()+"' where numeroCuenta="+help);
            db.query.execute("update personas set numeroCuenta="+p2.getNumerocuenta()+" where numeroCuenta="+help);
            db.query.execute("update personas set profesion='"+p2.getProfesion()+"' where numeroCuenta="+help);
            db.query.execute("update personas set lugarTrabajo='"+p2.getLugartrabajo()+"' where numeroCuenta="+help);
            db.query.execute("update personas set facultad='"+p2.getFacultad()+"' where numeroCuenta="+help);
            db.query.execute("update personas set tipoPersona='"+p2.getTipo()+"' where numeroCuenta="+help);
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        JOptionPane.showMessageDialog(null, "Lo modificaste!");
        nombre.setText("");
        apellido.setText("");
        edad.setText("");
        nacionalidad.setText("");
        residencia.setText("");
        cuenta.setText("");
        profesion.setText("");
        trabajo.setText("");
        facultad.setText("");
        modificar.setVisible(false);
        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jList1.getSelectedIndex() >= 0) {
            modificar.pack();
            modificar.setModal(true);
            modificar.setLocationRelativeTo(null);
            modificar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay nadie seleccionado para modificar");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8_AngelPonce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apellidocrear;
    private javax.swing.JDialog busquedalibre;
    private javax.swing.JDialog busquedaprimaria;
    private javax.swing.JDialog busquedatipo;
    private javax.swing.JComboBox<String> cbtipopersona;
    private javax.swing.JComboBox<String> cbtipopersona1;
    private javax.swing.JDialog crear;
    private javax.swing.JTextField cuenta;
    private javax.swing.JTextField cuentacrear;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField edadcrear;
    private javax.swing.JTextField facultad;
    private javax.swing.JTextField facultadcrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lugartrabajocrear;
    private javax.swing.JDialog modificar;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nacionalidadcrear;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombrecrear;
    private javax.swing.JTextField profesion;
    private javax.swing.JTextField profesioncrear;
    private javax.swing.ButtonGroup radio;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_f1;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_m1;
    private javax.swing.JTextField residencia;
    private javax.swing.JTextField residenciacrear;
    private javax.swing.JTextArea talibre;
    private javax.swing.JTextArea taprimaria;
    private javax.swing.JTextArea tatipos;
    private javax.swing.JTextField tflibre;
    private javax.swing.JTextField tfprimaria;
    private javax.swing.JTextField tftipo;
    private javax.swing.JTextField trabajo;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Personas> personas = new ArrayList();
    private ArrayList<Integer> cuentas = new ArrayList();
    private ArrayList tipos = new ArrayList();
}
